(part "8-338069-8"
    (packageRef "83380698")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
        (port "13" (symbPinId 13) (portName "13") (portType INOUT))
        (port "14" (symbPinId 14) (portName "14") (portType INOUT))
        (port "15" (symbPinId 15) (portName "15") (portType INOUT))
        (port "16" (symbPinId 16) (portName "16") (portType INOUT))
        (port "17" (symbPinId 17) (portName "17") (portType INOUT))
        (port "18" (symbPinId 18) (portName "18") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "8-338069-8")
    (property "Mouser_Part_Number" "571-8-338069-8")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/8-338069-8?qs=rb%252BOsUuIftz87g6y3haTiw%3D%3D")
    (property "Arrow_Part_Number" "8-338069-8")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/8-338069-8/te-connectivity?region=nac")
    (property "Description" "Body Features: Primary Product Color Red | Connector Profile Standard | Daisy Chain Without | Configuration Features: Number of Rows 2 | PCB Mount Orientation Vertical | Number of Positions 18 | Contact Features: PCB Contact Termination Area Plating Material Thickness 118.11  196.85 MICIN | Contact Underplating Material Nickel | Contact Current Rating (Max) 1.5 AMP | Contact Mating Area Plating Material Thickness 118.11  196.85 MICIN | Contact Mating Area Plating Material Tin | Contact Type Socket | C")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=4-1773457-1_050_Micro_MaTch&DocType=Data%20Sheet&DocLang=English&PartCntxt=8-338069-8&DocFormat=pdf")
    (property "symbolName1" "8-338069-8")
)
