(part "338069-8"
    (packageRef "3380698")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-338069-8")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/338069-8?qs=GhSsVVVq7dQLf4JKhIzYQA%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "338069-8")
    (property "Description" "Body Features: Connector Profile Standard | Daisy Chain Without | Primary Product Color Red | Configuration Features: Number of Rows 2 | PCB Mount Orientation Vertical | Number of Positions 8 | Contact Features: PCB Contact Termination Area Plating Material Finish Matte | Contact Mating Area Plating Material Thickness 3  5 MICM | PCB Contact Termination Area Plating Material Tin | Contact Mating Area Plating Material Tin | Contact Current Rating (Max) 1.5 AMP | Contact Base Material Phosphor Bronze | PCB")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=4-1773457-1_050_Micro_MaTch&DocType=Data%20Sheet&DocLang=English&PartCntxt=338069-8&DocFormat=pdf")
    (property "symbolName1" "338069-8")
)
